# Generated by Django 5.1.5 on 2025-02-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='contacts',
            new_name='contact_ids',
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks_json',
            field=models.TextField(default='[]'),
        ),
        migrations.DeleteModel(
            name='Subtask',
        ),
    ]
