# Generated by Django 5.1.5 on 2025-02-06 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_contacts_task_contact_ids_task_subtasks_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='contact_ids',
        ),
        migrations.AddField(
            model_name='task',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.contact'),
        ),
    ]
