# Generated by Django 5.1.5 on 2025-02-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_contact_ids_task_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('progress', 'In Progress'), ('feedback', 'Await Feedback'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
